# Kokkuvõte {.unnumbered}

*Natural Hygiene* ehk looduslik hügieen on liikumine, mis pühendub tervisele looduslike vahenditega.

Loodushügienistid lähtuvad 11-st põhimõttest, mis hõlmavad mõtteid elust, sotsiaalsetest suhetest, tervisest, bioloogiast ja toitumisest. Rõhutatakse, et igaühel on õigus puhtale ja saastamata kehale ning vabadusele ebanormaalsetest sundustest ja piirangutest.

Loodusliku hügieeni filosoofia sõnastas Isaac Jennings 1822. aastas. Muud liikumise juhtivad tegelased on olnud nt Sylvester Graham, Russell Thacher, Herbert McGolfin Shelton ja Terry Fry.

Loodushügienistid peavad toitumist ja tervist üksteisest lahutamatuks. Toitumine varustab, arendab ja säilitab organismi võimeid ja funktsioone optimaalsel tasemel. Toitumise kaudu organismid arenevad, kasvavad, paranevad, funktsioneerivad ja paljunevad. Loodushügienistid hindavad toitumist toidu komponentide omastamisena rakkude poolt, mitte eeltöödeldud toiduna, kuna ainult sel viisil saab organism kasu.

Kui seedimine on häiritud, on loodushügienistide arvates oluline kõrvaldada selle põhjused, mitte sümptomid.

Inimestele sobiva loodusliku toidu kriteeriumid hõlmavad mitte-toksilisust, toorelt söödavust, kergesti ja tõhusalt seeduvust, aluselisi ainevahetusreaktsioone, meeldivust, asendamatuid rasvhappeid, piisavalt valke, vitamiine, mineraalaineid ja vett ning energiavajaduste rahuldamist.

Inimesed peaksid toitu õigesti kombineerima, sööma õiges järjekorras ja piisavate minimaalsete ajavahemikega, et vältida ensüümide mõju tühistamist ja seedimistõrkeid.

Kuna valgud on mõeldud ennekõike kudede ehituseks ja hoolduseks, tuleks keha jaoks vajalik energia ammutada süsivesikutest. Süsivesikud on ühendid, mida leidub rohelistes taimedes, kust inimesed need toidu kaudu kätte saavad. Need jagunevad mono-, di- ja polüsahhariidideks. Inimese kehas suudetakse vahetult omastada üksnes monosahhariide.

Süsivesikud on olulised raku funktsionaalse aktiivsuse säilitamiseks ning rakkude varu- ja struktuurimaterjalina.

Toitumisteaduse seisukohalt on olulised monosahhariidid glükoos, fruktoos ja galaktoos, disahhariidid sukroos, maltoos ja laktoos ning polüsahhariidid tärklis, dekstriin, glükogeen ja tselluloos.

Peamised süsivesikute allikad on puuviljad, pähklid, mugulad, kaunviljad ja teraviljad. Puuviljadest sisaldavad süsivesikuid peamiselt magusad puuviljad, mis on magusad, alahappelised, happelised puuviljad ja melonid. Inimesed peaksid igapäevaselt sööma \qty{2,5}{\kg} puuvilju. Loodushügienistid loevad puuvilju inimese jaoks ideaalseks toiduks, sest need läbivad seedetrakti kiiresti eraldades monosahhariididest energiat, mida jääb üle muudeks tegevusteks kui seedimiseks, sisaldavad piisavas koguses maitsvat vett, kui tegemist pole just kuivatataud puuviljade või datlitega, neid pole vaja maitsestada ning nendes on sobilikus proportsioonis süsivesikud, valgud, vitamiinid ja mineraalained.

Köögiviljade puhul tuleb arvestada oblikhappe ja kaltsiumi suhtelise sisalduse suhtega, et ei tekiks neerukive. Kaariese, suhkrutõve ja hüpoglükeemia vältimiseks tuleb hoida töödeldud suhkrute ja muude töödeldud toitude tarbimisest.

Õige toitumise korral võib inimene olla kindel, et ta kehas toimub kõik nii, nagu peab.

Puuviljakultuur ja maheaiandus suudaksid maailma rahvastikku enam kui piisavalt toita, kui praegu toiduainete töötlemiseks kuluvaid finantse ja tööjõudu kasutataks hoopis puuviljade kasvatamiseks ja transportimiseks.
