# Setup of the project

## Getting the project files

After creating many projects using *bookdown*, i was ready to turn a project into a template. In order to turn a repository to a template, i went to GitHub, entered my project, chose *Settings* and checked *Template repository*. For a new project, i went to *New repository* and chose my template as *Repository template*. Another way to do the latter thing is to go to the main page of the template repository and click *Use this template*.

For projects inside an organisation, the project must be set to public in order to not having to use a password for cloning: *Settings* -> *General* -> *Danger Zone* -> *Change visibility*.

In RStudio Server, i created the new project: *File* -> *New Project…* -> *Version Control* -> *Git*, entered the HTTPS version of *Uniform Resource Locator* (URL) of my template repository for *Repository URL* and clicked *Create Project*.

RStudio Server doesn't rename the project metadata file *\*.Rproj* automatically. i did the rename manually and reopened the project: *File* -> *Open Project…*.

## Automated actions

For automation the [user-based actions after the user has an account](#user-based-actions-after-adding-user), i created a script that should be run if the manual set-up is too overwhelming:

```{bash eval = FALSE}
sudo ~/rstudio-projects/create-project.sh <subdomain>

```

This is the content of that file written in Shell Command Language [@introduction] using @bakker_2022_named:

```{sh eval = FALSE}
programname=$0

function usage {
    echo ""
    echo "This program automates creating a new RStudio Server project."
    echo ""
    echo "usage: $programname --project string --user string"
    echo ""
    echo "  --project string   name of the project"
    echo "                          (example: loodusteaduste-klubi)"
    echo "  --user string            the user in GitHub"
    echo "                          (example: Tome-Kit)"
    echo ""
}

function die {
    printf "Script failed: %s\n\n" "$1"
    exit 1
}

while [ $# -gt 0 ]; do
    if [[ $1 == "--help" ]]; then
        usage
        exit 0
    elif [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done

if [[ -z $project ]]; then
    usage
    die "The name of the project is missing."
elif [[ -z $user ]]; then
    usage
    die "The name of the user in GitHub is missing."
fi

folder_of_project="/home/kalmer/rstudio-projects/$project"
git clone https://github.com/$user/$project $folder_of_project
ssh-keygen -N '' -f ~/.ssh/$project -q

tee ~/.ssh/github.com/$project > /dev/null <<EOF                                                                                                                                                                                                                                
Host github.com-$project                                                                                                                                                                                                                                                        
     HostName github.com                                                                                                                                                                                                                                                        
     User git                                                                                                                                                                                                                                                                   
     IdentityFile ~/.ssh/$project                                                                                                                                                                                                                                               
EOF                                                                                                                                                                                                                                                                             

configuration_file_for_git="$folder_of_project/.git/config"
sed -i "s/https:\/\//git@/" $configuration_file_for_git
sed -i "s/github.com\//github.com-$project:/" $configuration_file_for_git

## Configuration of the content                                                                                                                                                                                                                                                 
name_of_original_project="manual-for-rstudio"
sed_for_renaming_project="s/$name_of_original_project/$project/"

path_to_bookdown_yml="$folder_of_project/_bookdown.yml"

sed -i $sed_for_renaming_project $path_to_bookdown_yml

sed -i "/\"rmd\//d" $path_to_bookdown_yml
rm $folder_of_project/rmd/*

path_to_output_yml="$folder_of_project/_output.yml"
sed -i "s/piiskop/$user/" $path_to_output_yml
sed -i $sed_for_renaming_project $path_to_output_yml

sed -i $sed_for_renaming_project $folder_of_project/js.js

## Web output                                                                                                                                                                                                                                                                   

configuration_file="/etc/nginx/sites-available/$project.tennis24.ee"
sudo cp /etc/nginx/sites-available/manual-for-rstudio.tennis24.ee $configuration_file
sudo sed -i "s/manual-for-rstudio/$project/g" $configuration_file
sudo ln -s $configuration_file "/etc/nginx/sites-enabled/$project.tennis24.ee"
sudo systemctl reload nginx

```

On the line 64 of the previous script, there is `sed` command which can be used for deleting unnecessary lines [@a2023_sed]. The command on the particular line deletes all the lines from the file *_bookdown.yml* in the project folder that contain the text *"rmd/"* because the files in the folder *rmd* are project-specific.

## User-based actions

The following actions must be performed for every editor of the repository.

For a new user:

```{bash eval = FALSE}
sudo adduser <username>

```

If instead of `adduser` the command `useradd` would be used then the password and home folder must be set manually.

[]{#user-based-actions-after-adding-user}

In order to push into the remote repository i need to create a key that can be used to unlock the lock to the repository in GitHub. i let to generate the key:

```{bash eval = FALSE}
ssh-keygen

```

This command first generates the following output:

> Generating public/private rsa key pair.  
> Enter file in which to save the key (/home/<username>/.ssh/id_rsa):

As i have many projects in GitHub i need to have many keys as one key can't be used for many projects. Therefore, i also write a new file name for the key:

```
/home/<username>/.ssh/<name-of-project>

```

If instead of the full path only the file name would be set then that file would be created into the home folder and for further actions with Secure Shell (SSH) its folder must be created manually.

The content of the newly created public key must be copied into GitHub for the named project as deploying the key by also allowing write access. i also have to inform my server about the connections of the newly created key by adding the following lines into *~/.ssh/config*:

```
Host github.com-<name-of-project>
 HostName github.com
 User git
 IdentityFile ~/.ssh/<name-of-project>

```

So far, *git* has no information on the newly cloned project about it's credentials. i need to tell it this information in order to be able to push my changes into the remote repository by changing the file *.git/config* inside my project's folder by setting a new value for *url*:

```
url = git@github.com-<name-of-project>:<username-in-github>/<name-of-project>.git

```

From now on, it's possible to edit the newly created project and push its changes into GitHub.

Inside RStudio Server, i want to make some changes right at the beginning before the first building as it's a new project. One of them is to change the name of the output file in *\_bookdown.yml*:

```
book_filename: "<name-of-project>" 

```

The same filename must be entered into *js.js*:

```{verbatim label = "js"}
  createLink(div, "book-print", "<name-of-project>.pdf", "View printable book");


```

i might want to delete all the files inside *rmd* subfolder and their references in `rmd_files`:

```
rmd_files: [
  "index.Rmd",
  "references.Rmd"
]

```

Samuti tasub koheselt muuta faili *README.md* sisu projektile vastavaks.

i need to update the repository Uniform Resource Locator (URL) in *\_output.yml* for `bookdown::bs4_book`:

```
repo: https://github.com/<username-in-github>/<name-of-project>

```
